### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bluryface** [ChronosSF/SimplePowerDisplay#1]
I have used NibPointDisplay since it first came out and up until patch 7.0 have never had any issues with this addon. I downloaded SimplePointDisplay and did all the edits and followed all instructions as posted. It did indeed use my holy power settings from NibPointDisplay. However, upon logging out of the game on my paladin and then logging back in, while the addon is still loading, all display of holy power has disappeared. In other words once I relog, the addon does not work. Reinstalling the addon from stratch and reconfiguring everything by hand, instead of using my Nib settings, results in the addon working again but once I relog, the addon has stopped displaying holy power again. I have deleted and reinstalled the addon a dozen times and redid all configuration within the addon and still once i relog, all holy power does not display. I have cleared my cache and tried many things but still same result. Initially the addon works great but upon relogging it stops working. For starters, your zip file unzips with a folder titled "SimplePointDisplay-master" which is not a recognized naming convention. In order to make the addon appear you must first edit the folder title removing "-master". Once this is done, the game recognizes and  lists the addon. However, none of this solves the issue that the addon works great but stops working the moment I relog. Any ideas on what I can do to fix the issue of the addon not working after relogging? Thank you for your efforts in continuing this addon. BTW, I also noticed that after relogging and going to config mode, the configuration boxes are missing elements. Entering config mode does not display an example of my holy power position etc.

**Comment by ChronosSF** [comment]
Could you please attach your config file - `<wow-installation-directory>\WTF\Account\<acc name>\SavedVariables\SimplePowerDisplay.lua`

Yes, GitHub affixes the branch name to the ZIP file (-master in this case). I'll update the install guide. The addon should be available through curse and wowinterface soon anyway - this is just a temporary way of distributing it.

**Comment by bluryface** [comment]
It won't let me attach lua or zip files so the following is the contents of SimplePowerDisplay.lua from my account / saved variables folder:

SimplePointDisplayDB = {
    ["profileKeys"] = {
        ["MyName - Mal'Ganis"] = "PALADIN",
    },
    ["profiles"] = {
        ["MyName - Mal'Ganis"] = {
            ["PALADIN"] = {
                ["types"] = {
                    ["hp"] = {
                        ["configmode"] = {
                            ["enabled"] = true,
                            ["count"] = 5,
                        },
                        ["bars"] = {
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0.0235294117647059,
                                            ["g"] = 0.0235294117647059,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.0117647058823529,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 10,
                                    ["width"] = 50,
                                },
                            }, -- [1]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0.0235294117647059,
                                            ["g"] = 0.0235294117647059,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.0117647058823529,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 15,
                                    ["width"] = 50,
                                },
                            }, -- [2]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.862745098039216,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.0117647058823529,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 20,
                                    ["width"] = 50,
                                },
                            }, -- [3]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.874509803921569,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.0117647058823529,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 25,
                                    ["width"] = 50,
                                },
                            }, -- [4]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.992156862745098,
                                            ["r"] = 0.00392156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.0117647058823529,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 40,
                                    ["width"] = 50,
                                },
                            }, -- [5]
                        },
                        ["general"] = {
                            ["hideempty"] = true,
                            ["hideui"] = true,
                            ["direction"] = {
                                ["vertical"] = true,
                            },
                        },
                        ["position"] = {
                            ["y"] = -25,
                            ["x"] = -111,
                        },
                    },
                },
            },
        },
        ["Default"] = {
            ["GENERAL"] = {
                ["types"] = {
                    ["cp"] = {
                        ["enabled"] = false,
                    },
                },
            },
            ["WARLOCK"] = {
                ["types"] = {
                    ["ss"] = {
                        ["enabled"] = false,
                    },
                },
            },
            ["PALADIN"] = {
                ["types"] = {
                    ["hp"] = {
                        ["configmode"] = {
                            ["count"] = 5,
                            ["enabled"] = false,
                        },
                        ["general"] = {
                            ["direction"] = {
                                ["vertical"] = true,
                            },
                            ["hideui"] = true,
                            ["hideempty"] = true,
                        },
                        ["position"] = {
                            ["y"] = -25,
                            ["x"] = -111,
                        },
                        ["bars"] = {
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["r"] = 0.992156862745098,
                                            ["g"] = 0.0235294117647059,
                                            ["b"] = 0.0235294117647059,
                                        },
                                        ["maxcolor"] = {
                                            ["r"] = 0.0117647058823529,
                                            ["b"] = 0,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 10,
                                    ["width"] = 50,
                                },
                            }, -- [1]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["r"] = 0.992156862745098,
                                            ["g"] = 0.0235294117647059,
                                            ["b"] = 0.0235294117647059,
                                        },
                                        ["maxcolor"] = {
                                            ["r"] = 0.0117647058823529,
                                            ["b"] = 0,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 15,
                                    ["width"] = 50,
                                },
                            }, -- [2]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["r"] = 0.992156862745098,
                                            ["g"] = 0.862745098039216,
                                            ["b"] = 0,
                                        },
                                        ["maxcolor"] = {
                                            ["r"] = 0.0117647058823529,
                                            ["b"] = 0,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 20,
                                    ["width"] = 50,
                                },
                            }, -- [3]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["r"] = 0.992156862745098,
                                            ["g"] = 0.874509803921569,
                                            ["b"] = 0,
                                        },
                                        ["maxcolor"] = {
                                            ["r"] = 0.0117647058823529,
                                            ["b"] = 0,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 25,
                                    ["width"] = 50,
                                },
                            }, -- [4]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["r"] = 0.00392156862745098,
                                            ["g"] = 0.992156862745098,
                                            ["b"] = 0,
                                        },
                                        ["maxcolor"] = {
                                            ["r"] = 0.0117647058823529,
                                            ["b"] = 0,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 40,
                                    ["width"] = 50,
                                },
                            }, -- [5]
                        },
                        ["enabled"] = true,
                    },
                },
            },
        },
        ["PALADIN"] = {
            ["WARLOCK"] = {
                ["types"] = {
                    ["ss"] = {
                        ["enabled"] = false,
                    },
                },
            },
            ["PALADIN"] = {
                ["types"] = {
                    ["hp"] = {
                        ["configmode"] = {
                            ["count"] = 5,
                        },
                        ["general"] = {
                            ["hideempty"] = true,
                            ["hideui"] = true,
                            ["direction"] = {
                                ["vertical"] = true,
                            },
                        },
                        ["position"] = {
                            ["y"] = -25,
                            ["x"] = -111,
                        },
                        ["bars"] = {
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.0156862745098039,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.00784313725490196,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 10,
                                    ["width"] = 50,
                                },
                            }, -- [1]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.0156862745098039,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.00784313725490196,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 15,
                                    ["width"] = 50,
                                },
                            }, -- [2]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.87843137254902,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.00784313725490196,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 20,
                                    ["width"] = 50,
                                },
                            }, -- [3]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.870588235294118,
                                            ["r"] = 0.992156862745098,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.00784313725490196,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 25,
                                    ["width"] = 50,
                                },
                            }, -- [4]
                            {
                                ["position"] = {
                                    ["gap"] = 1,
                                },
                                ["bg"] = {
                                    ["full"] = {
                                        ["color"] = {
                                            ["b"] = 0,
                                            ["g"] = 0.992156862745098,
                                            ["r"] = 0.0117647058823529,
                                        },
                                        ["maxcolor"] = {
                                            ["b"] = 0,
                                            ["r"] = 0.00784313725490196,
                                        },
                                    },
                                },
                                ["size"] = {
                                    ["height"] = 40,
                                    ["width"] = 50,
                                },
                            }, -- [5]
                        },
                    },
                },
            },
            ["GENERAL"] = {
                ["types"] = {
                    ["cp"] = {
                        ["enabled"] = false,
                    },
                },
            },
        },
    },
}

**Comment by bluryface** [comment]
Please note, I did edit my name from the file after paste but that is the only edit I made to the contents. Really appreciate your assistance with this as I love this addon....Cheers

**Comment by ChronosSF** [comment]
Got it, Will try to figure it out during the weekend. Thanks for trying the addon out!

**Comment by ChronosSF** [comment]
From what I gathered it was probably a combination of the addon's name not matching how it registers in AceDB and the Ace libs being very outdated in the package.

Try getting the latest version again. Just have in mind I changed the name to cPointDisplay so you'll have to follow the installation steps with the new name.

Let me know if it still doesn't save on exit.

**Comment by bluryface** [comment]
Okay, so here is what I did. I downloaded the new version and unzipped the file. I edited out the "-master" from the title of the folder so that the title of the addon folder now reads "cPointDisplay". Rather than attempt to rename stuff in order to retain my configuration for the addon, I chose to simply configure the addon from scratch, to my preferred settings and look. I have been testing, logging in and out and other testing for some time now. I don't know what was changed in the current version of the addon but IT WORKS! Perhaps the Ace libs were the issue before? Oddly, ingame the addon does not appear in alphabetical order. However, after some extensive testing over the past hour, I can report that the addon is now working correctly, even after relogging. Thank you very much for taking on this addon. I have been using it since its inception, many years ago. I am sure, once the word gets out there, that this addon will be very popular. The previous problems I was experiencing with the addon are now resolved. Thank you again for your efforts....Cheers

**Comment by ChronosSF** [comment]
Glad it works for you now! The libs definitely needed updating and that was the likely cause. It became very apparent when I started configuring it from scratch and had to fight all sorts of exceptions I didn't notice when using my nibPointDisplay profiles.

Anyhow, with this out of the way I can now start re-implementing the other power types.
