### ISSUE TITLE
Deeper Stratagem Support

### ISSUE THREAD

**Issue by s9th** [ChronosSF/SimplePowerDisplay#10]
Is it possible to add support for Deeper Stratagem rogue talent, i.e. the one which grants 1 additional combo point?

**Comment by ChronosSF** [comment]
I'll see what I can do. Unfortunately, rogue is the only class I don't have a high level character in, so not sure how I'll be able to test it.

**Comment by s9th** [comment]
If you have level 45, it should be enough since deeper stratagem is tier 3 talent

**Comment by ChronosSF** [comment]
I saw I have old code for something similar - Monk with Ascension. Might just mod the rogue path to something similar and let you test it ;)

**Comment by s9th** [comment]
I can pull a branch from git if needed and maybe even modify to make a pull request

**Comment by ChronosSF** [comment]
Give #11 a try if you know how. If I remember correctly the underlying code from nibPointDisplay was able to switch between the two ComboPoints configs on the fly (at least when I was testing this with my WW Monk). If this doesn't work though, I will have to try it with a rogue of my own.

**Comment by s9th** [comment]
So far configuration works partially (everything visual, but not the "Show at 0 points") and gameplay does not work as well. I'll try to make a fix, but if I fail, I'll tell you

**Comment by s9th** [comment]
Okay, I screwed up somewhere on forking or pull request, so it shows that I changed everything.
In reality there is only one change on line 517
if (CurType == "cp") or (CurType == "cp6") then

**Comment by ChronosSF** [comment]
Your git is probably configured to commit with different line endings that what the file currently is with.

**Comment by ChronosSF** [comment]
Yeh, I see what I missed on line 517 :) . Thanks for the heads up.

I am updating my PR with your change and will see what's wrong with Show at 0

**Comment by s9th** [comment]
It actually fixed everything. Show at 0 also relied on combo points updating which it didn't

**Comment by ChronosSF** [comment]
Cool. Ok my PR should be good now. If you see anything let me know. Otherwise I'll push an update to Curse tomorrow.
