### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by wheatbread** [ChronosSF/SimplePowerDisplay#14]
Got the following errors after updating to v8.0.3r:

`1x Error loading cPointDisplay\Libs\AceGUI-3.0-36-SharedMediaWidgets\SoundWidget.lua
`
 `1x Error loading cPointDisplay\Libs\AceGUI-3.0-36-SharedMediaWidgets\StatusbarWidget.lua`

 `1x Error loading cPointDisplay\Libs\AceGUI-3.0-36-SharedMediaWidgets\BorderWidget.lua`

`1x Error loading cPointDisplay\Libs\AceGUI-3.0-36-SharedMediaWidgets\BackgroundWidget.lua`

`2x Error loading cPointDisplay\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0-6010002.lua`

**Comment by ChronosSF** [comment]
Do these happen all the time? Any particular thing I can do to make them pop up?

As they are loading errors you could also try to reinstall the addon to see if this makes them go away.

**Comment by s9th** [comment]
Can confirm, this bug exists. Happens every time on load.
If you disable all other addons, cPointDisplay cannot find and instance of LibSharedMedia-3.0.
If you look at LSM folder structure inside Libs - and also Acewidgets-SharedMedia - there is something strange there.

If you fix structure of these folders, everything is dandy

**Comment by wheatbread** [comment]
Sorry, just now saw your question.

I tried a complete reinstall just now, deleting the saved variable files as well.  I am still getting the 7 errors upon loading in.  

https://imgur.com/a/hUgSn5b

**Comment by ChronosSF** [comment]
Thank you guys, I'll see what happens. I use a lot of addons so depending on how WoW does dependencies it might be loading the LibSharedMedia from a shared pool that another addon fills appropriately. Should be easy to work it out.

**Comment by ChronosSF** [comment]
@s9th , @wheatbread , if you like you can test #15 to see if it fixes the reported issues

Otherwise I am going to merge and make a release tomorrow.

**Comment by ChronosSF** [comment]
I uploaded the new release on Curse. It'll take some time for it to get approved. Please, let me know if it fixes the reported issues.
