### ISSUE TITLE
Add support for chi (Windwalker Monks)

### ISSUE THREAD

**Issue by ChronosSF** [ChronosSF/SimplePowerDisplay#3]

**Comment by Ag3ntunkn0wn** [comment]
is this project dead? been waiting for chi to be added for awhile now.

**Comment by ChronosSF** [comment]
No, but I prioritized doing work on the other addon I resurrected for Legion - SLDT. I'll get back to Chi support soon. So many stuff to do in Legion though... :)

**Comment by ChronosSF** [comment]
How did the original addon play around Ascension though? Checking the old code it seems it didn't support the talent at all (only went up to 5 points). 

I can hardcode it to 6 then do some logic hiding the 6th bar regardless of settings when Ascension is not chosen. This, however, won't make it possible for the total size of all bars together to be the same - it almost looks like it either has to have 2 separate settings for each bar - one with and one without Ascension or have a totally different setup for Chi where there is a total width / height that the bars should take and then divide by 5 or 6 based on the talent...

This is another reason I've been avoiding Chi to be honest. Can't think of a really nice way to support Ascension.

**Comment by ChronosSF** [comment]
After thinking about it for a while I think I'll go with two seperate Chi displays - one with and one without Ascension and they'll swap automatically when the player changes talents. The two will have completely separate options but you could always copy options from one power type to another so setting both up won't be super tedious.

You can expect a working version later today.

**Comment by ChronosSF** [comment]
Should be fine now, hope you like it.
